### ISSUE TITLE
Add status page with current backend service status retrieval

### ISSUE THREAD

**Issue by piopon** [piopon/web-scraper#32]
We must add a separate status page to scraper and a link to it from the main page (maybe at the bottom footer?)

**Comment by Vishnudas2003** [comment]
Hello there!

I would like to take on this task. Could you please assign it to me ?

Cheers!
Vishnu Das Puthukudi

**Comment by piopon** [comment]
IDEA: Maybe it would be nice to add something like a output data preview (on-demand) in form of a dialog/popup window showing the JSON structure in a form of a expandable nested tree or something like that

**Comment by Vishnudas2003** [comment]
okey got it thanks !!

**Comment by Vishnudas2003** [comment]
Can I work on it ??

**Comment by piopon** [comment]
> Can I work on it ??. Its for one of my college project

Hello 👋 
Sorry, but I wanted to do it by myself from start to finish.
But of course feel free to fork this repo and implement changes on your own account 😉
